require_relative './config/environment'
require 'sinatra/activerecord/rake'

desc "Start our app console"
task :console do
  Pry.start
end

namespace :greetings do
  desc "Say hi to everyone"
  task :say_hi do
    puts "Hi there! You're pretty good looking. <3"
  end

  desc "Say goodbye"
  task :say_goodbye do
    puts 'See ya'
  end
end